version: "3"
services:

  postgres:
    image: "postgres"
    container_name: "dbPosc"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_USER: ${POSTGRES_USER:-root}
    networks:
      - my-net
      
  students:
    build: firstDocker
    ports:
      - "8080:8080"
    networks:
     - my-net

 

networks:
  my-net:
    driver: bridge

